openapi: 3.0.3
info:
  title: ChatBB MongoDB API Contracts
  description: API contracts for MongoDB operations after mongo.ts refactoring
  version: 1.0.0
  contact:
    name: ChatBB Development Team

servers:
  - url: http://localhost:4321/api
    description: Local development server

paths:
  /occurrenceCountByState:
    get:
      summary: Get occurrence counts by Brazilian state
      description: Returns aggregated occurrence data grouped by Brazilian states with optional taxonomic filtering
      parameters:
        - name: genus
          in: query
          schema:
            type: string
          description: Filter by genus name
        - name: specificEpithet
          in: query
          schema:
            type: string
          description: Filter by specific epithet
        - name: scientificName
          in: query
          schema:
            type: string
          description: Filter by scientific name
        - name: kingdom
          in: query
          schema:
            type: string
            enum: [Plantae, Animalia, Fungi]
          description: Filter by kingdom
        - name: forceRefresh
          in: query
          schema:
            type: boolean
            default: false
          description: Force refresh cache instead of using cached results
      responses:
        '200':
          description: Successful response with occurrence counts
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of occurrences
                  regions:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          description: Brazilian state name
                        count:
                          type: integer
                          description: Number of occurrences in this state
        '500':
          description: Database connection or query error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /taxaCountByState:
    get:
      summary: Get taxa counts by Brazilian state
      description: Returns taxonomic data aggregated by Brazilian states with filtering
      parameters:
        - name: genus
          in: query
          schema:
            type: string
          description: Filter by genus name
        - name: specificEpithet
          in: query
          schema:
            type: string
          description: Filter by specific epithet
        - name: scientificName
          in: query
          schema:
            type: string
          description: Filter by scientific name
        - name: kingdom
          in: query
          schema:
            type: string
            enum: [Plantae, Animalia, Fungi]
          description: Filter by kingdom
      responses:
        '200':
          description: Successful response with taxa counts
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of taxa
                  regions:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          description: Brazilian state name
                        count:
                          type: integer
                          description: Number of taxa in this state
        '500':
          description: Database connection or query error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /taxa:
    get:
      summary: List taxa with pagination
      description: Returns paginated list of taxonomic records
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
          description: Page number (0-based)
        - name: kingdom
          in: query
          schema:
            type: string
            enum: [Plantae, Animalia, Fungi]
          description: Filter by kingdom
        - name: taxonomicStatus
          in: query
          schema:
            type: string
          description: Filter by taxonomic status
      responses:
        '200':
          description: Successful response with paginated taxa
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      description: Taxon record
                  total:
                    type: integer
                    description: Total number of records
                  totalPages:
                    type: integer
                    description: Total number of pages
        '500':
          description: Database connection or query error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /family/{kingdom}:
    get:
      summary: Get families by kingdom
      description: Returns family statistics for a specific kingdom
      parameters:
        - name: kingdom
          in: path
          required: true
          schema:
            type: string
            enum: [Plantae, Animalia, Fungi]
          description: Kingdom name
      responses:
        '200':
          description: Successful response with family data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Family name
                    count:
                      type: integer
                      description: Number of species in this family
        '400':
          description: Invalid kingdom parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Database connection or query error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    TaxaFilter:
      type: object
      description: Filter object for taxonomic queries
      additionalProperties:
        oneOf:
          - type: string
          - type: object
            description: RegExp object for pattern matching

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error
