openapi: 3.0.3
info:
  title: Biodiversidade.Online - Taxa API
  description: |
    API para consulta de dados taxonômicos transformados da Flora, Funga e Fauna do Brasil.

    Esta API serve dados da collection MongoDB `taxa` (transformada), que contém registros
    validados e enriquecidos dos catálogos oficiais (Flora e Funga do Brasil, Catálogo 
    Taxonômico da Fauna do Brasil).

    **Rastreabilidade**: Cada registro pode ser rastreado à sua fonte original via `_id` 
    na collection `taxa_ipt` (dados brutos sem transformações).
  version: 2.0.0
  contact:
    name: Biodiversidade.Online
    url: https://biodiversidade.online

servers:
  - url: http://localhost:4321/api
    description: Servidor de desenvolvimento local
  - url: https://biodiversidade.online/api
    description: Servidor de produção

tags:
  - name: Taxa
    description: Operações sobre dados taxonômicos

paths:
  /taxa:
    get:
      summary: Lista táxons com filtros
      description: |
        Retorna lista paginada de táxons filtrados por parâmetros de busca.

        **Filtros aplicados automaticamente:**
        - Apenas registros com `taxonRank` em ['ESPECIE', 'VARIEDADE', 'FORMA', 'SUB_ESPECIE']
        - Apenas registros de `kingdom` em ['Animalia', 'Plantae', 'Fungi']
      tags:
        - Taxa
      operationId: listTaxa
      parameters:
        - name: scientificName
          in: query
          description: Nome científico completo ou parcial (case-insensitive)
          required: false
          schema:
            type: string
            example: Panthera onca

        - name: canonicalName
          in: query
          description: Nome canônico (genus + specificEpithet) - busca exata
          required: false
          schema:
            type: string
            example: Panthera onca

        - name: kingdom
          in: query
          description: Reino taxonômico
          required: false
          schema:
            type: string
            enum: [Animalia, Plantae, Fungi]
            example: Animalia

        - name: family
          in: query
          description: Família taxonômica
          required: false
          schema:
            type: string
            example: Felidae

        - name: genus
          in: query
          description: Gênero taxonômico
          required: false
          schema:
            type: string
            example: Panthera

        - name: taxonRank
          in: query
          description: Categoria taxonômica
          required: false
          schema:
            type: string
            enum: [ESPECIE, VARIEDADE, FORMA, SUB_ESPECIE]
            example: ESPECIE

        - name: taxonomicStatus
          in: query
          description: Status taxonômico
          required: false
          schema:
            type: string
            example: ACEITO

        - name: threatStatus
          in: query
          description: Filtrar apenas espécies com algum status de ameaça
          required: false
          schema:
            type: boolean
            example: true

        - name: invasive
          in: query
          description: Filtrar apenas espécies invasoras
          required: false
          schema:
            type: boolean
            example: true

        - name: limit
          in: query
          description: Número máximo de resultados por página
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
            example: 50

        - name: offset
          in: query
          description: Número de registros a pular (para paginação)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
            example: 0

      responses:
        '200':
          description: Lista de táxons retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - pagination
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Taxon'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
              example:
                data:
                  - _id: 'taxon-12345'
                    taxonID: 'taxon-12345'
                    scientificName: 'Panthera onca (Linnaeus, 1758)'
                    canonicalName: 'Panthera onca'
                    kingdom: 'Animalia'
                    phylum: 'Chordata'
                    class: 'Mammalia'
                    order: 'Carnivora'
                    family: 'Felidae'
                    genus: 'Panthera'
                    specificEpithet: 'onca'
                    taxonRank: 'ESPECIE'
                    taxonomicStatus: 'ACEITO'
                    vernacularname:
                      - vernacularName: 'onça-pintada'
                        language: 'Português'
                    threatStatus:
                      source: 'faunaAmeacada'
                      category: 'VU'
                pagination:
                  total: 150
                  limit: 100
                  offset: 0
                  hasMore: true

        '400':
          description: Parâmetros de consulta inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Invalid parameter'
                message: "Parameter 'limit' must be between 1 and 1000"

        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /taxa/{taxonID}:
    get:
      summary: Obtém táxon por ID
      description: |
        Retorna detalhes completos de um táxon específico pelo seu `taxonID`.

        **Rastreabilidade**: O `_id` retornado é idêntico ao da collection `taxa_ipt`,
        permitindo auditoria do dado original via query:
        `db.taxa_ipt.findOne({_id: "<taxonID>"})`
      tags:
        - Taxa
      operationId: getTaxonById
      parameters:
        - name: taxonID
          in: path
          description: Identificador único do táxon
          required: true
          schema:
            type: string
            example: 'taxon-12345'

      responses:
        '200':
          description: Táxon encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Taxon'
              example:
                _id: 'taxon-12345'
                taxonID: 'taxon-12345'
                scientificName: 'Panthera onca (Linnaeus, 1758)'
                canonicalName: 'Panthera onca'
                flatScientificName: 'pantheraonca'
                kingdom: 'Animalia'
                phylum: 'Chordata'
                class: 'Mammalia'
                order: 'Carnivora'
                family: 'Felidae'
                genus: 'Panthera'
                specificEpithet: 'onca'
                taxonRank: 'ESPECIE'
                taxonomicStatus: 'ACEITO'
                higherClassification: 'Chordata'
                vernacularname:
                  - vernacularName: 'onça-pintada'
                    language: 'Português'
                  - vernacularName: 'jaguar'
                    language: 'Inglês'
                distribution:
                  origin: 'nativa'
                  occurrence: ['AC', 'AM', 'PA', 'MT', 'MS']
                  countryCode: ['BR']
                threatStatus:
                  source: 'faunaAmeacada'
                  category: 'VU'
                _transformedAt: '2025-10-29T10:30:00.000Z'
                _transformVersion: '2.0.0'

        '404':
          description: Táxon não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: 'Not found'
                message: "Taxon with ID 'invalid-id' not found"

        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /taxa/count:
    get:
      summary: Conta táxons com filtros
      description: |
        Retorna contagem de táxons que correspondem aos filtros especificados.
        Aceita os mesmos filtros que `/taxa` (exceto limit/offset).
      tags:
        - Taxa
      operationId: countTaxa
      parameters:
        - name: scientificName
          in: query
          schema:
            type: string
        - name: kingdom
          in: query
          schema:
            type: string
            enum: [Animalia, Plantae, Fungi]
        - name: family
          in: query
          schema:
            type: string
        - name: genus
          in: query
          schema:
            type: string
        - name: taxonRank
          in: query
          schema:
            type: string
            enum: [ESPECIE, VARIEDADE, FORMA, SUB_ESPECIE]
        - name: threatStatus
          in: query
          schema:
            type: boolean
        - name: invasive
          in: query
          schema:
            type: boolean

      responses:
        '200':
          description: Contagem retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                required:
                  - count
                  - filters
                properties:
                  count:
                    type: integer
                    description: Número total de táxons que correspondem aos filtros
                    example: 150
                  filters:
                    type: object
                    description: Filtros aplicados na contagem
                    example:
                      kingdom: 'Animalia'
                      family: 'Felidae'

        '400':
          description: Parâmetros de consulta inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Taxon:
      type: object
      required:
        - _id
        - taxonID
        - scientificName
        - canonicalName
        - kingdom
        - taxonRank
      properties:
        _id:
          type: string
          description: Identificador único (idêntico ao taxonID)
          example: 'taxon-12345'

        taxonID:
          type: string
          description: ID taxonômico do DwC-A original
          example: 'taxon-12345'

        scientificName:
          type: string
          description: Nome científico completo com autor e ano
          example: 'Panthera onca (Linnaeus, 1758)'

        canonicalName:
          type: string
          description: Nome canônico (genus + specificEpithet + infraspecificEpithet)
          example: 'Panthera onca'

        flatScientificName:
          type: string
          description: Nome científico sem caracteres especiais, lowercase
          example: 'pantheraonca'

        kingdom:
          type: string
          enum: [Animalia, Plantae, Fungi]
          description: Reino taxonômico
          example: 'Animalia'

        phylum:
          type: string
          description: Filo taxonômico
          example: 'Chordata'

        class:
          type: string
          description: Classe taxonômica
          example: 'Mammalia'

        order:
          type: string
          description: Ordem taxonômica
          example: 'Carnivora'

        family:
          type: string
          description: Família taxonômica
          example: 'Felidae'

        genus:
          type: string
          description: Gênero taxonômico
          example: 'Panthera'

        specificEpithet:
          type: string
          description: Epíteto específico
          example: 'onca'

        infraspecificEpithet:
          type: string
          description: Epíteto infraespecífico (para variedades, subespécies)
          example: 'meridionalis'

        taxonRank:
          type: string
          enum: [ESPECIE, VARIEDADE, FORMA, SUB_ESPECIE]
          description: Categoria taxonômica
          example: 'ESPECIE'

        taxonomicStatus:
          type: string
          description: Status taxonômico (ACEITO, SINÔNIMO, etc)
          example: 'ACEITO'

        higherClassification:
          type: string
          description: Classificação hierárquica superior (processada)
          example: 'Chordata'

        vernacularname:
          type: array
          description: Nomes vernaculares (normalizados)
          items:
            type: object
            properties:
              vernacularName:
                type: string
                description: Nome vernacular (lowercase com hífens)
                example: 'onça-pintada'
              language:
                type: string
                description: Idioma (capitalizado)
                example: 'Português'

        distribution:
          oneOf:
            - $ref: '#/components/schemas/FloraDistribution'
            - $ref: '#/components/schemas/FaunaDistribution'

        othernames:
          type: array
          description: Sinônimos e outros nomes relacionados
          items:
            type: object
            properties:
              taxonID:
                type: string
              scientificName:
                type: string
              taxonomicStatus:
                type: string

        threatStatus:
          type: object
          description: Status de ameaça (agregado de fontes externas)
          properties:
            source:
              type: string
              enum: [cncfloraFungi, cncfloraPlantae, faunaAmeacada]
            category:
              type: string
              description: Categoria de ameaça

        invasiveStatus:
          type: object
          description: Status de espécie invasora
          properties:
            isInvasive:
              type: boolean
            source:
              type: string
              enum: [invasoras]

        conservationUnits:
          type: array
          description: Unidades de conservação onde a espécie ocorre
          items:
            type: object
            properties:
              ucName:
                type: string
                description: Nome da unidade de conservação

        _transformedAt:
          type: string
          format: date-time
          description: Timestamp da última transformação
          example: '2025-10-29T10:30:00.000Z'

        _transformVersion:
          type: string
          description: Versão do script de transformação usado
          example: '2.0.0'

    FloraDistribution:
      type: object
      description: Distribuição geográfica para Flora/Fungi
      properties:
        origin:
          type: string
          description: Origem (nativa, cultivada, etc)
          example: 'nativa'
        Endemism:
          type: string
          description: Endemismo
        phytogeographicDomains:
          type: object
          description: Domínios fitogeográficos
        occurrence:
          type: array
          description: Locais de ocorrência (locationID ordenado)
          items:
            type: string
          example: ['N', 'NE', 'CO', 'SE', 'S']
        vegetationType:
          type: object
          description: Tipo de vegetação

    FaunaDistribution:
      type: object
      description: Distribuição geográfica para Fauna
      properties:
        origin:
          type: string
          description: Origem
          example: 'nativa'
        occurrence:
          type: array
          description: Localidades (split por ';')
          items:
            type: string
          example: ['Amazônia', 'Cerrado', 'Pantanal']
        countryCode:
          type: array
          description: Códigos de países (split por ';')
          items:
            type: string
          example: ['BR', 'AR', 'PY']

    Pagination:
      type: object
      required:
        - total
        - limit
        - offset
        - hasMore
      properties:
        total:
          type: integer
          description: Número total de registros que correspondem aos filtros
          example: 150
        limit:
          type: integer
          description: Número de registros por página
          example: 100
        offset:
          type: integer
          description: Número de registros pulados
          example: 0
        hasMore:
          type: boolean
          description: Indica se há mais páginas disponíveis
          example: true

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Tipo do erro
          example: 'Invalid parameter'
        message:
          type: string
          description: Mensagem descritiva do erro
          example: "Parameter 'limit' must be between 1 and 1000"
        details:
          type: object
          description: Detalhes adicionais sobre o erro
