openapi: 3.0.3
info:
  title: Occurrence Count by State API
  description: API para contagem de ocorrências de espécies por estado brasileiro
  version: 1.0.0
  contact:
    name: Biodiversidade.Online

servers:
  - url: https://biodiversidade.online/api
    description: Servidor de produção
  - url: http://localhost:4321/api
    description: Servidor de desenvolvimento

paths:
  /occurrenceCountByState:
    get:
      summary: Obter contagens de ocorrências por estado brasileiro
      description: |
        Retorna contagens agregadas de registros de ocorrências de espécies
        por estado brasileiro, com suporte a filtros taxonômicos.
      operationId: getOccurrenceCountByState
      parameters:
        - name: kingdom
          in: query
          description: Filtro por reino taxonômico
          required: false
          schema:
            type: string
            example: 'Animalia'
        - name: phylum
          in: query
          description: Filtro por filo taxonômico
          required: false
          schema:
            type: string
            example: 'Chordata'
        - name: class
          in: query
          description: Filtro por classe taxonômica
          required: false
          schema:
            type: string
            example: 'Mammalia'
        - name: order
          in: query
          description: Filtro por ordem taxonômica
          required: false
          schema:
            type: string
            example: 'Primates'
        - name: superfamily
          in: query
          description: Filtro por superfamília taxonômica
          required: false
          schema:
            type: string
            example: 'Hominoidea'
        - name: family
          in: query
          description: Filtro por família taxonômica
          required: false
          schema:
            type: string
            example: 'Felidae'
        - name: genus
          in: query
          description: Filtro por gênero taxonômico
          required: false
          schema:
            type: string
            example: 'Panthera'
        - name: specificEpithet
          in: query
          description: Filtro por epíteto específico
          required: false
          schema:
            type: string
            example: 'onca'
      responses:
        '200':
          description: Contagens de ocorrências obtidas com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OccurrenceCountResponse'
              examples:
                success:
                  summary: Exemplo de resposta bem-sucedida
                  value:
                    total: 15432
                    regions:
                      - _id: 'São Paulo'
                        count: 3245
                      - _id: 'Minas Gerais'
                        count: 2891
                      - _id: 'Rio de Janeiro'
                        count: 1876
                      - _id: 'Bahia'
                        count: 1654
                empty_results:
                  summary: Exemplo sem resultados
                  value:
                    total: 0
                    regions: []
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                database_error:
                  summary: Erro de conexão com banco de dados
                  value:
                    error: 'Falha ao conectar ao banco de dados'
                server_error:
                  summary: Erro interno genérico
                  value:
                    error: 'Erro interno do servidor'

components:
  schemas:
    OccurrenceCountResponse:
      type: object
      required:
        - total
        - regions
      properties:
        total:
          type: integer
          minimum: 0
          description: Número total de registros de ocorrência encontrados
          example: 15432
        regions:
          type: array
          description: Lista de contagens por estado
          items:
            $ref: '#/components/schemas/RegionCount'

    RegionCount:
      type: object
      required:
        - _id
        - count
      properties:
        _id:
          type: string
          description: Nome normalizado do estado brasileiro
          example: 'São Paulo'
          pattern: '^[A-Za-zÀ-ÿ ]+$'
        count:
          type: integer
          minimum: 0
          description: Número de registros de ocorrência no estado
          example: 3245

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Mensagem de erro em português
          example: 'Falha ao conectar ao banco de dados'

  examples:
    TaxonomicFilters:
      summary: Exemplo de filtros taxonômicos combinados
      value:
        kingdom: 'Animalia'
        class: 'Mammalia'
        family: 'Felidae'

    NoFilters:
      summary: Consulta sem filtros (todos os registros)
      value: {}

tags:
  - name: Occurrence
    description: Operações relacionadas a registros de ocorrência
