package duckstore

import (
	"context"
	"database/sql"
	"fmt"
)

// ddlStatements creates the fixed Darwin Core schema: two core tables, six
// taxon extension tables, and one ingest audit table. Executed once at
// startup via CREATE TABLE IF NOT EXISTS so repeated runs are idempotent.
var ddlStatements = []string{
	`CREATE TABLE IF NOT EXISTS taxon (
		"taxonID" VARCHAR PRIMARY KEY,
		"scientificName" VARCHAR,
		"scientificNameAuthorship" VARCHAR,
		"acceptedNameUsageID" VARCHAR,
		"parentNameUsageID" VARCHAR,
		"originalNameUsageID" VARCHAR,
		"kingdom" VARCHAR,
		"phylum" VARCHAR,
		"class" VARCHAR,
		"order" VARCHAR,
		"family" VARCHAR,
		"genus" VARCHAR,
		"subgenus" VARCHAR,
		"specificEpithet" VARCHAR,
		"infraspecificEpithet" VARCHAR,
		"taxonRank" VARCHAR,
		"verbatimTaxonRank" VARCHAR,
		"nomenclaturalCode" VARCHAR,
		"taxonomicStatus" VARCHAR,
		"nomenclaturalStatus" VARCHAR,
		"namePublishedIn" VARCHAR,
		"namePublishedInYear" VARCHAR,
		"higherClassification" VARCHAR,
		"taxonRemarks" VARCHAR,
		"references" VARCHAR,
		"modified" TIMESTAMP,
		"canonicalName" VARCHAR,
		"flatScientificName" VARCHAR,
		"datasetID" VARCHAR,
		"datasetName" VARCHAR,
		"ingestRunId" VARCHAR,
		"ingestedAt" TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS occurrence (
		"occurrenceID" VARCHAR PRIMARY KEY,
		"basisOfRecord" VARCHAR,
		"catalogNumber" VARCHAR,
		"recordNumber" VARCHAR,
		"recordedBy" VARCHAR,
		"individualCount" BIGINT,
		"sex" VARCHAR,
		"lifeStage" VARCHAR,
		"occurrenceStatus" VARCHAR,
		"preparations" VARCHAR,
		"associatedMedia" VARCHAR,
		"associatedSequences" VARCHAR,
		"associatedTaxa" VARCHAR,
		"eventDate" TIMESTAMP,
		"eventTime" VARCHAR,
		"year" BIGINT,
		"month" BIGINT,
		"day" BIGINT,
		"verbatimEventDate" VARCHAR,
		"habitat" VARCHAR,
		"samplingProtocol" VARCHAR,
		"fieldNumber" VARCHAR,
		"fieldNotes" VARCHAR,
		"eventRemarks" VARCHAR,
		"continent" VARCHAR,
		"country" VARCHAR,
		"countryCode" VARCHAR,
		"stateProvince" VARCHAR,
		"county" VARCHAR,
		"municipality" VARCHAR,
		"locality" VARCHAR,
		"verbatimLocality" VARCHAR,
		"minimumElevationInMeters" VARCHAR,
		"maximumElevationInMeters" VARCHAR,
		"verbatimElevation" VARCHAR,
		"minimumDepthInMeters" VARCHAR,
		"maximumDepthInMeters" VARCHAR,
		"decimalLatitude" DOUBLE,
		"decimalLongitude" DOUBLE,
		"geodeticDatum" VARCHAR,
		"coordinateUncertaintyInMeters" DOUBLE,
		"coordinatePrecision" VARCHAR,
		"verbatimCoordinates" VARCHAR,
		"verbatimLatitude" VARCHAR,
		"verbatimLongitude" VARCHAR,
		"georeferencedBy" VARCHAR,
		"georeferenceProtocol" VARCHAR,
		"georeferenceVerificationStatus" VARCHAR,
		"identifiedBy" VARCHAR,
		"dateIdentified" TIMESTAMP,
		"identificationRemarks" VARCHAR,
		"taxonID" VARCHAR,
		"scientificName" VARCHAR,
		"scientificNameAuthorship" VARCHAR,
		"kingdom" VARCHAR,
		"phylum" VARCHAR,
		"class" VARCHAR,
		"order" VARCHAR,
		"family" VARCHAR,
		"genus" VARCHAR,
		"specificEpithet" VARCHAR,
		"infraspecificEpithet" VARCHAR,
		"taxonRank" VARCHAR,
		"vernacularName" VARCHAR,
		"taxonRemarks" VARCHAR,
		"institutionCode" VARCHAR,
		"collectionCode" VARCHAR,
		"ownerInstitutionCode" VARCHAR,
		"datasetName" VARCHAR,
		"datasetID" VARCHAR,
		"informationWithheld" VARCHAR,
		"dataGeneralizations" VARCHAR,
		"dynamicProperties" VARCHAR,
		"otherCatalogNumbers" VARCHAR,
		"occurrenceRemarks" VARCHAR,
		"hasSuspectCoordinates" BOOLEAN,
		"ingestRunId" VARCHAR,
		"ingestedAt" TIMESTAMP
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_distribution (
		"taxonID" VARCHAR,
		"origin" VARCHAR,
		"endemism" VARCHAR,
		"phytogeographicDomains" VARCHAR[],
		"vegetationType" VARCHAR[],
		"countryCode" VARCHAR[],
		"occurrence" VARCHAR[],
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_species_profile (
		"taxonID" VARCHAR,
		"lifeForm" VARCHAR[],
		"habitat" VARCHAR[],
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_vernacular_name (
		"taxonID" VARCHAR,
		"vernacularName" VARCHAR,
		"language" VARCHAR,
		"locality" VARCHAR,
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_reference (
		"taxonID" VARCHAR,
		"bibliographicCitation" VARCHAR,
		"title" VARCHAR,
		"creator" VARCHAR,
		"date" VARCHAR,
		"type" VARCHAR,
		"identifier" VARCHAR,
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_types_and_specimen (
		"taxonID" VARCHAR,
		"locality" VARCHAR,
		"recordedBy" VARCHAR,
		"catalogNumber" VARCHAR,
		"collectionCode" VARCHAR,
		"source" VARCHAR,
		"typeStatus" VARCHAR,
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS taxon_resource_relationship (
		"taxonID" VARCHAR,
		"relatedTaxonID" VARCHAR,
		"scientificName" VARCHAR,
		"taxonomicStatus" VARCHAR,
		FOREIGN KEY ("taxonID") REFERENCES taxon("taxonID")
	)`,
	`CREATE TABLE IF NOT EXISTS ingest_runs (
		"id" VARCHAR PRIMARY KEY,
		"source" VARCHAR,
		"tipo" VARCHAR,
		"binary" VARCHAR,
		"version" VARCHAR,
		"startedAt" TIMESTAMP,
		"finishedAt" TIMESTAMP,
		"durationSec" DOUBLE,
		"status" VARCHAR,
		"exitCode" INTEGER,
		"errorMessage" VARCHAR,
		"dryRun" BOOLEAN,
		"dwcaUrl" VARCHAR,
		"dwcaDownloadedBytes" BIGINT,
		"dwcaPackageId" VARCHAR,
		"dwcaPubDate" VARCHAR,
		"dwcaVersion" VARCHAR,
		"dwcaTitle" VARCHAR,
		"recordsRead" BIGINT,
		"recordsRejected" BIGINT,
		"recordsInserted" BIGINT,
		"recordsUpdated" BIGINT,
		"recordsUpserted" BIGINT,
		"recordsRemoved" BIGINT,
		"recordsWithSuspectCoordinates" BIGINT,
		"recordsWithUnknownFields" BIGINT,
		"warnings" VARCHAR
	)`,
}

func createSchema(ctx context.Context, db *sql.DB) error {
	for _, stmt := range ddlStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("exec ddl: %w", err)
		}
	}
	return nil
}
