# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# Default agents to run when --agents is not specified
default_agents = ["copilot", "claude", "cursor", "codex"]

# Enable nested rule loading from nested .ruler directories
# Perfect for monorepos with component-specific rules
nested = true

# --- Agent Specific Configurations ---
# You can enable/disable agents and override their default output paths here.

[agents.copilot]
enabled = true
output_path = ".github/copilot-instructions.md"

[agents.claude]
enabled = true
output_path = "CLAUDE.md"

[agents.cursor]
enabled = true
output_path = ".cursor/rules/ruler_cursor_instructions.mdc"

[agents.codex]
enabled = true
output_path = "AGENTS.md"

[agents.codex.mcp]
enabled = true
merge_strategy = "merge"

# --- MCP Servers ---
# Define Model Context Protocol servers here for enhanced AI context

# [mcp_servers.filesystem]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-filesystem"]
# env = { NODE_OPTIONS = "--no-deprecation" }

# [mcp_servers.git]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-git", "--repository"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]
