name: Deno Deploy
on:
  push:
    branches:
      - main
    paths: ['web/**', '.github/workflows/deno-deploy.yml']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./web
        run: yarn

      - name: Build Astro
        working-directory: ./web
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
        run: yarn run build

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload to Deno Deploy
        working-directory: ./web
        run: |
          deno install --allow-all --no-check -r -f https://deno.land/x/deploy/deployctl.ts
          cd dist
          deployctl deploy --project=${{secrets.DENO_DEPLOY_PROJECT}} --token=${{secrets.DENO_DEPLOY_TOKEN}} --prod ./server/entry.mjs
